language: ruby
rvm:
    - 2.2
branches:
    only:
        develop
env:
    - SCRIPTS_DIR=_scripts
    - WIKIBOOK_DIR=_wikibook
before_script:
    - $TRAVIS_BUILD_DIR/$SCRIPTS_DIR/before_script.sh
deploy:
    local_dir: _site
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    target_branch: master
    fqdn: cs241.cs.illinois.edu
    on:
        branch: develop
