language: ruby
rvm:
    - 2.2
branches:
    only:
        develop
env:
    - REPO=illinois-cs241/illinois-cs241.github.io
before_script:
    - ls .
    - _script/before_script.sh
deploy:
    local_dir: _site
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    target_branch: master
    fqdn: cs241.cs.illinois.edu
    on:
        branch: develop
